---
title: "Data Type"
output: html_notebook
---

# Datatypes 

Datatypes in the dataset are:

 1. PatientAge
Results taken from patients aged 40 - 95 years old.  
 2. Anaemia
Boolean when true representing the red blood cell count in the patient.A patient is considered having aneamia if haematocrit levels are below 36%. 
 3. CreatininePhosphokinaseLevel
Level of CPK protein in the blood in mcg/L.
 4. Diabetes
Boolean when true representing the patient having from diabetes. 
 5. EjectionFraction
The percentage of the total volume pumped out by the left heart chamber.
 6. HighBloodPressure
Boolean representing the patient having High Blood Pressure (hypertension).
 7. Platelets
Level of platelets in the blood in kiloplatelets/ml.
 8. CreatineSerumLevel
Level of serum creatine in the blood in mg/dL.
 9. SodiumSerumLevel
Level of serum Sodium in the blood in mEq/l
 10. Sex
Boolean representing the sex, 1 is men and 0 is woman. 100 men and 190 woman participated in the study. 
 11. Smoking
Boolean representing the smoking behavior, true if smoking. 
 12. Time
Time in days representing the days before the follow-up examination. 
 13. DeathEvent
Boolean states if the patient died or survived before the end of the follow up period.

